export const config = {
    CLOUDINARY_UPLOAD_PRESET: import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET,
    CLOUDINARY_CLOUD_NAME: import.meta.env.VITE_CLOUDINARY_CLOUD_NAME ,
    CLOUDINARY_API_URL: import.meta.env.VITE_CLOUDINARY_API_URL,
    API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
    
}